### ISSUE TITLE
[ 공통논의 ] 컨텐츠 전체 화면 정중앙에 배치

### ISSUE THREAD

**Issue by suwan98** [like-lion-javascript-project-9/enter-euid#24]
## 목적
> 컨텐츠 전체 화면 정중앙에 배치하는 것에 대한 논의사항
## 작업 상세 내용
> enterEuid 자체가 모바일로 설계된거라서 웹에서는 여백이 생길 수 밖에 없습니다. 따라서 화면 정중앙에 배치한후, 해당 바깥 여백에 대한 backgroundColor를 흰색보다 더 진한 회색계열의 색으로 지정해서 개발하면 어떨지 의견드립니다!

**Comment by cfgop23** [comment]
template.html 파일에 중앙에 배치 되게 세팅했습니다.
코드는 다음과 같습니다.
`<div
      class="absolute left-1/2 top-1/2 h-screen max-h-[690px] min-w-[320px] max-w-max -translate-x-1/2 -translate-y-1/2 bg-slate-300"
    ></div>`
