### ISSUE TITLE
[ layout ] layout 공통 width 사이즈 지정

### ISSUE THREAD

**Issue by jellyjoji** [like-lion-javascript-project-9/enter-euid#29]
[ layout ] 

[ layout 공통 width 사이즈 지정 ] 

목적 : 
layout 의 최소 width 사이즈는 320px로 지정합니다. 

해당 이슈를 적은 이유 :
모바일 디바이스의 최소 사이즈를 기준으로 잡아 모든 기기에서 화면이 잘리는 현상이 생기지 않도록 합니다.

작업상세내용 : 
layout 의 최소 width 사이즈는 320px로 지정합니다. 
최소사이즈 320px 을 기반으로 반응형으로 크기가 커지도록 CSS 를 설계합니다.

**Comment by suwan98** [comment]
```js
@media (min-width: 769px)  {
  html {
    font-size: 20px;
  }
}
```
사이즈가 커질때 font-size가 변경되는걸로 이슈를 수정했습니다
