### ISSUE TITLE
[ 공통사항 ] js/lib/dom/index.js 내부에서 불필요한 파일 제거

### ISSUE THREAD

**Issue by suwan98** [like-lion-javascript-project-9/enter-euid#33]
## 목적
>  js/lib/dom/index.js 내부에서 불필요한 파일 제거

## 작업 상세 내용
> 해당 파일에 경로와 상관없는 불필요한 파일이 포함되어 있어 제거하였고, data.json에서 오탈자가 발견되어 수정했습니다

## 추가사항
> 해당 파일 .export * from '../../js/partials/userList.js' 과  export * from './swiper.js'

![image](https://github.com/like-lion-javascript-project-9/enter-euid/assets/122072365/bb8d8206-a51a-4aae-82a9-43a74a8203e9)

**Comment by cfgop23** [comment]
확인했습니다.
