### ISSUE TITLE
[ home ] swiper 오류 현상에 대한 이슈

### ISSUE THREAD

**Issue by jellyjoji** [like-lion-javascript-project-9/enter-euid#34]
## swiper 오류 현상에 대한 이슈
home 페이지 작업 중 swiper 적용 후 디바이스 사이즈를 줄였을때 페이지 내 모든 이미지가 사라지는 현상이 발견되었습니다. 

## 작업 상세 내용
![image](https://github.com/like-lion-javascript-project-9/enter-euid/assets/74365275/6272ae39-c0af-4135-af3b-94901a6cde35)

## 추가사항
해당 오류에 대한 원인과 해결점을 아신다면 문의부탁드립니다.

**Comment by suwan98** [comment]
해당 가장 최상위 부모인 <div swiper> 부분의 width를 수정하는 것으로 해결하였습니다.
