### ISSUE TITLE
[ home ] json data 오타 수정 요청

### ISSUE THREAD

**Issue by jellyjoji** [like-lion-javascript-project-9/enter-euid#39]
## 작업 상세 내용
json data 의 key 값 네이밍 "address" 에  철자 오타가 있는것을 발견했습니다. 
추후 pull request 에 철자 수정하여 요청하도록 하겠습니다.
adress -> address
![image](https://github.com/like-lion-javascript-project-9/enter-euid/assets/74365275/07b96dfb-7f6c-4098-8ff7-957e16706445)

**Comment by suwan98** [comment]
오탈자 수정 완료했습니다

**Comment by suwan98** [comment]
오탈자 수정 완료했습니다
