### ISSUE TITLE
[ maindetail 페이지 ]  데이터 화면 렌더링 시 성능 이슈

### ISSUE THREAD

**Issue by suwan98** [like-lion-javascript-project-9/enter-euid#59]
## 목적
>
데이터를 받아 화면에 렌더링 시 이미지의 원본크기가 너무 커서 렌더링하는데 시간이 엄청나게 소요되는 문제 발생
## 작업 상세 내용
>
해결방안 찾아서 해결 예정
## 추가사항
>
![image](https://github.com/like-lion-javascript-project-9/enter-euid/assets/122072365/5d88ccd3-80bd-4b49-aa93-fb1968a8db6f)

**Comment by cfgop23** [comment]
미디어 쿼리 삭제했습니다
